In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [28]:
data=pd.read_excel(r'C:\Users\vodla\Downloads\Incois\20230324_VU_GeoFishCatch_2008_2017.xlsx')

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3210 entries, 0 to 3209
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FID                 854 non-null    float64
 1   TYPE                784 non-null    object
 2   SECTOR_NAME         979 non-null    object
 3   STATION_NAME        834 non-null    object
 4   FISHING_START       3210 non-null   object
 5   SHOOT_LAT           3210 non-null   float64
 6   SHOOT_LONG          3210 non-null   float64
 7   DIASTANCE           394 non-null    object
 8   DIRECTION           1802 non-null   object
 9   ANGLE               249 non-null    object
 10  DEPTH               2136 non-null   object
 11  MAJOR_SPECIES       3174 non-null   object
 12  TOTAL_CATCH         3185 non-null   object
 13  Unnamed: 13         0 non-null      float64
 14  Unnamed: 14         1409 non-null   object
 15  Unnamed: 15         0 non-null      float64
 16  Unnamed: 16         0 non-null      float64
 17  Unnamed: 17         0 non-null      float64
 18  Revised_totalcatch  3131 non-null   float64
 19  Unnamed: 19         0 non-null      float64
 20  Unnamed: 20         0 non-null      float64
 21  (catch is in kg)    0 non-null      float64
dtypes: float64(11), object(11)
memory usage: 551.8+ KB

In [30]:
data = data[['FISHING_START', 'SHOOT_LAT', 'SHOOT_LONG', 'TOTAL_CATCH', 'MAJOR_SPECIES']].copy()

In [31]:
data[data.duplicated(keep=False)].sort_values(by=['FISHING_START', 'SHOOT_LAT', 'SHOOT_LONG', 'TOTAL_CATCH', 'MAJOR_SPECIES'])

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
416,2011-06-30 00:00:00,12.790128,80.386450,35kg,Euthynnus affinis
417,2011-06-30 00:00:00,12.790128,80.386450,35kg,Euthynnus affinis
405,2011-07-02 00:00:00,12.744219,80.463053,75kg,Euthynnus affinis
406,2011-07-02 00:00:00,12.744219,80.463053,75kg,Euthynnus affinis
424,2011-12-04 00:00:00,12.943303,80.320286,20kg,Sepia pharaonis
...,...,...,...,...,...
1103,14.06.2012,17.030000,83.340000,"72,","yellowfin tuna,"
2424,21.01.2016,9.580000,76.140000,750,"Anchovy,"
2428,21.01.2016,9.580000,76.140000,750,"Anchovy,"
2423,21.01.2016,10.070000,76.060000,250,"Rachycentron canadum,"
2427,21.01.2016,10.070000,76.060000,250,"Rachycentron canadum,"

In [32]:
data.drop_duplicates(subset=['FISHING_START', 'SHOOT_LAT', 'SHOOT_LONG', 'TOTAL_CATCH', 'MAJOR_SPECIES'], inplace=True)

In [33]:
data

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
0,2009-02-19 00:00:00,18.455278,84.431111,390,"Longfish(200), Ponyfish(90), Nemipters(50), Up..."
1,2009-02-14 00:00:00,18.445000,84.494167,1000,"Drab crocker(500), Mackeral(200), Dieddaba(200..."
2,2009-02-19 00:00:00,18.240833,84.161667,500,"Pomfret(400), Ponyfish(100)"
3,2009-02-12 00:00:00,17.993611,83.774444,550,"Drab croaker(200), Nemipters(125), Upenius(125..."
4,2009-03-08 00:00:00,17.708056,83.390000,95,"Drabcrocker(50), Nemipters(20), Lizardfish(10)..."
...,...,...,...,...,...
3205,13.10.2016,11.374000,80.092000,"7,2,1,","Sardinella longiceps,Siganus sp.,Leiognathus d..."
3206,03.11.2016,11.331000,80.431000,"5,2,3,1,","Sardinella longiceps,Sardinella albella,Sardin..."
3207,23.08.2016,11.196000,81.509000,"15,24,5,3,","Scomberoides commersonianus,Sardinella longice..."
3208,13.10.2016,11.405000,80.254000,"15,9,5,8,11,6,","Sardinella longiceps,Siganus sp.,Carangoides s..."
3209,03.11.2016,11.338000,80.607000,"7,6,15,7,4,","Sardinella gibbosa,Carangoides sp.,Sardinella ..."

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3150 entries, 0 to 3209
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FISHING_START  3150 non-null   object
 1   SHOOT_LAT      3150 non-null   float64
 2   SHOOT_LONG     3150 non-null   float64
 3   TOTAL_CATCH    3125 non-null   object
 4   MAJOR_SPECIES  3114 non-null   object
dtypes: float64(2), object(3)
memory usage: 147.7+ KB

In [35]:
temp_dates = pd.to_datetime(data['FISHING_START'],dayfirst= True, errors='coerce').astype(object)

In [36]:
data[temp_dates.isnull()]

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
2352,21/05/2014 12.30.00,15.5260,70.260833,"28,","Xiphias gladius,"
2360,24/06/2014 12.30,19.9225,67.775333,"8,","Carcharhinus limbatus,"
3156,17-03-2017 13.28,21.2700,88.560000,"50,100,","Eleutheronema tetradactylum,Setipinna phasa,"

In [37]:
temp_dates.fillna(data['FISHING_START'], inplace=True)

In [38]:
temp_dates=temp_dates.astype(str).str.replace('.', ':', regex=False).str.replace('/', '-', regex=False)

In [39]:
temp_dates = pd.to_datetime(temp_dates,format='mixed', errors='coerce')

In [40]:
temp_dates.isnull().sum()

np.int64(0)

In [41]:
data['FISHING_START'] = temp_dates

In [42]:
final=data.copy()

In [43]:
final

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
0,2009-02-19,18.455278,84.431111,390,"Longfish(200), Ponyfish(90), Nemipters(50), Up..."
1,2009-02-14,18.445000,84.494167,1000,"Drab crocker(500), Mackeral(200), Dieddaba(200..."
2,2009-02-19,18.240833,84.161667,500,"Pomfret(400), Ponyfish(100)"
3,2009-02-12,17.993611,83.774444,550,"Drab croaker(200), Nemipters(125), Upenius(125..."
4,2009-03-08,17.708056,83.390000,95,"Drabcrocker(50), Nemipters(20), Lizardfish(10)..."
...,...,...,...,...,...
3205,2016-10-13,11.374000,80.092000,"7,2,1,","Sardinella longiceps,Siganus sp.,Leiognathus d..."
3206,2016-11-03,11.331000,80.431000,"5,2,3,1,","Sardinella longiceps,Sardinella albella,Sardin..."
3207,2016-08-23,11.196000,81.509000,"15,24,5,3,","Scomberoides commersonianus,Sardinella longice..."
3208,2016-10-13,11.405000,80.254000,"15,9,5,8,11,6,","Sardinella longiceps,Siganus sp.,Carangoides s..."
3209,2016-11-03,11.338000,80.607000,"7,6,15,7,4,","Sardinella gibbosa,Carangoides sp.,Sardinella ..."

In [44]:
final[final['TOTAL_CATCH'].isnull()]

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
127,2011-02-06 00:00:00,17.823427,72.540148,NaN,No Catch
128,2011-03-04 00:00:00,17.878400,72.652592,NaN,No Catch
135,2011-02-08 00:00:00,18.163787,72.604992,NaN,No Catch
136,2011-02-06 00:00:00,18.229675,72.372807,NaN,No Catch
176,2011-01-21 00:00:00,19.472040,71.707283,NaN,"Acetus(5), Sciaenids(10), lobster(3no)"
178,2011-01-18 00:00:00,19.496167,71.629568,NaN,No Catch
187,2011-01-17 00:00:00,19.710870,71.097062,NaN,No Catch
197,2011-01-14 00:00:00,19.730717,71.079340,NaN,No Catch
198,2011-03-05 00:00:00,19.733312,71.093557,NaN,No Catch
202,2011-01-18 00:00:00,19.748867,71.092920,NaN,No Catch
209,2011-01-13 00:00:00,19.379867,71.868347,NaN,No Catch
216,2011-01-17 00:00:00,19.408289,71.741806,NaN,No Catch
229,2011-01-24 00:00:00,19.487317,71.719247,NaN,No Catch
244,2011-01-31 00:00:00,19.724214,71.095458,NaN,No Catch
245,2011-03-07 00:00:00,19.724214,71.095458,NaN,No Catch
344,2008-10-05 00:00:00,9.250000,76.333056,NaN,NaN
347,2008-10-05 00:00:00,9.333056,76.366667,NaN,NaN
382,2008-10-05 00:00:00,9.150000,76.316667,NaN,NaN
946,2007-12-13 00:00:00,15.330354,73.704413,NaN,Oil sardine
948,2007-12-24 00:00:00,15.123300,73.680485,NaN,Mackerel
961,2007-11-11 00:00:00,14.752361,73.841173,NaN,Indian Mackerel
962,2007-11-11 00:00:00,15.027568,73.952895,NaN,Indian Mackerel
1032,2013-09-27 00:00:00,17.370000,83.510000,NaN,NaN
1643,2014-02-05 10:30:00,11.385006,92.168342,NaN,"No fish,"
2082,2014-06-27 00:00:00,11.550000,75.150000,NaN,"Horse mackerel, Alepes djeddaba"

In [45]:
np.set_printoptions(threshold=np.inf)
final['TOTAL_CATCH'].unique()

array(['390', '1000', '500', '550', '95', '46', '18', '90', '96', '34',
       '121', '151', '98', '124', '190', '240', '55', '60', '220', '150',
       '184', '126', '2235', '2505', '3150', '3270', '3860', '3345',
       '1485', '3200', '3700', '1600', '4250', '1840', '2497', '2250',
       '3950', '2075', '3785', '1980', '4793', '3215', '2265', '3140',
       '2255', '12140', '2245', '2135', '4140', '3260', '10800', '3040',
       '3105', '3525', '3990', '2450', '1056kgs', '1472kgs', '2387kgs',
       '384kgs', '1312kgs', '352kgs', '1088kgs', '440kgs', '664kgs',
       '1344kgs', '544kgs', '704kgs', '889kgs', '769kgs', '1440kgs',
       '700kgs', '650kgs', '1251kgs', '1578kgs', '2110kgs', '928kgs',
       '3535kgs', '1286kgs', '326kgs', '556kgs', '1280kgs', '5536kgs',
       '444kgs', '733kgs', '862kgs', '370kgs', '964kgs', '672kgs',
       '485kgs', '2538kgs', '1920kgs', '1434kgs', '744kgs', '706kgs',
       '832kgs', '2470kgs', '1119kgs', '1111kgs', '256kgs', '1959kgs',
       '3300kgs', '864kgs', '1458kgs', '1556kgs', '6250kgs', '3227kgs',
       '2850kgs', '3107kgs', '1856kgs', '35kg', '30kg', '15kg', '10kg',
       nan, '25kg', '15Kg', '5kg', '50kg', '20kg', '45kg', '55kg', '6kg',
       '26kg', '23kg', '75kg', '28kg', '63kg', '67kg', '19kg', '1No',
       '60kg', '145kg', '65kg', '125kg', '80kg', '20Kg', '18kg', '270kg',
       '202kg', '100kg', '170kg', '700kg', '280kg', '4800kg', '1100kg',
       '1700kg', '300kg', '2200kg', '450kg', '950kg', '175kg', '1200kg',
       '2100kg', '590kg', '120kg', '350kg', '1800kg', '250kg', '1300kg',
       '900kg', '200kg', '375kg', '1050kg', '400kg', '1400kg', '1950kg',
       '1250kg', '600kg', '500kg', '3100kg', '750kg', '275kg', '150kg',
       '210kg', '1075kg', '780kg', '310kg', '3000kg', '435kg', '3950kg',
       '2075kg', '3370kg', '190kg', '180kg', '4100kg', '3800kg', '380kg',
       '800kg', '2700kg', '1650kg', '8000kg', '475kg', '410kg', '550kg',
       '90kg', '5000kg', '2000kg', '220kg', '70kg', '156kg', '130kg',
       '158kg', '83kg', '73kg', '22kg', '48kg', '330kg', '30Kg', '4kg',
       '154kg', '260kg', '85kg', '74kg', '40kg', '42kg', '105kg', '370kg',
       '328kg', '160kg', '12kg', '255kg', '123kg', '98kg', '320kg',
       '95kg', '3500kg', '295kg', '5200kg', '4000kg', '629.5kg', '3300kg',
       '5100kg', '2500kg', '3600kg', '4300kg', '2800kg', '3200kg',
       '3900kg', '4500kg', '4700kg', '3700kg', '37kg', '520kg', '2900kg',
       '650kg', '43kg', '203kg', '484kg', '480kg', '4150kg', '2450kg',
       '548kg', '490kg', '4400kg', '110kg', '6000kg', '205kg', '835kg',
       '240kg', '230kg', '3400kg', '302kg', '5010kg', '1417kg', '2600kg',
       '430kg', '440kg', '4200kg', '33kg', '251kg', '285kg', '417kg',
       '510kg', '3250kg', '51kg', '5700kg', '390kg', '570kg', '290kg',
       '365kg', '329kg', '294kg', '340kg', '3850kg', '2420kg', '1235kg',
       '3230kg', '244kg', '4650kg', '248kg', '530kg', '458kg', '820kg',
       '2950kg', '3020kg', '1000kg', '428kg', '598kg', '4350kg', '962kg',
       '4050kg', '2190kg', '3532kg', '245kg', '115kg', '4600kg', '4250kg',
       '1ton500kg', '1ton', '3.5kg', '6ton', '0.6ton', '1.2ton', '5ton',
       '3ton', '3.5ton', '4.5ton', '5.5ton', '1.5ton', '4ton', '2ton',
       '2.5ton', '1500kg', '7ton', '7000kg', '8ton', '6.5ton', '6-8ton',
       '12000kg', '12ton', '7.5ton', 1000, 750, 500250500500, 2500, 600,
       3000, 1200, 500800, '500, 1500, 300', '200, 1200, 1000',
       '0.2,,0.1,,,0.6,1.5,,,,,,,,,,,,,,0.1,,,,2,,,0.5,,,,,,,0.15,,0.5,,,,0.3,0.1,0.2,0.2,0.4,,72.8,',
       'Catch(kgs),2,,0.1,0,,,0.8,0.1,0.2,,2.5,,1,,3.5,0.1,0.2,,,,0.1,0,0.2,,2,0.5,0.5,0.5,0.5,,0,,0.1,0,1.3,,2,0.3,0,0.5,3,0.2,0.2,4,0.5,4,125.8,',
       'Catch(kgs),0.2,0.1,0.2,1.5,0,0,0,0.15,,,0.2,0.1,0.1,,2,0.2,0.15,0.1,,0.5,0.8,,0.1,2,,0.5,,1.5,,2,0.1,,,0.2,0.2,,3,,0.15,1.5,0.5,0.1,0.1,10,2,3,380.7,',
       'Catch(kgs),0.5,,0.5,0,0.2,0.1,0.1,0,0.1,,1.5,,1,,2.5,,,,0.1,0.2,,0.1,,1,0.2,0.1,0.2,,0.5,0,,0.2,,,0.1,,2.5,2,,3.5,3,,0.1,3,2,4,70.2,',
       'Catch(kgs),0,0.1,,0.5,,,,,,,0.2,,0.1,,2,,0.1,,,0.5,,0.1,,,4,0.5,,1.5,,2,0.1,,0.1,0.2,0.2,,4,,,,0.5,0.1,0.1,6,2,3,158.2,',
       'Catch(kgs),2,,0.2,2,0.1,,0.2,,0.1,0.1,2.5,0.3,0.5,,3,0.2,,0.1,0.2,0.3,0.2,,0.3,2,,,0.2,,0.5,4,,0.1,,0.1,,,2,0.5,0.1,2,2,,0.2,2,4,6,243.8,',
       'Catch(kgs),2.5,,,0.5,,,0,0.05,,0.1,2,,0.8,,4,,,,0.1,0.2,0.1,0.2,0,,0,0,0.1,0,0.8,,0.5,,0,0.5,0,,1,1,0.2,2,2,0,0,5,1,2,240.1,',
       'Catch(kgs),1,,,,,,,0.2,,,4,,2,0.3,2,0.3,0.2,,,,0.1,0.2,,3,1,0,0,,0,0,0.2,0,0.8,0.1,0.2,0.15,4,4,,0,1,,0,5,8,7,198.6,',
       'Catch(kgs),1.5,,,,,,,0,,,0.5,,0.5,0,1,,,,,0.5,,0.1,,1.5,0,0.5,0.5,,0.8,1,0,0,0,0.2,0.5,0,3,2,,5,2,,0.1,3,5,1.5,402.1,',
       '1.0, 0.2, 0.3, 0.2, 1.5, 1.0, 3.0, 1.5, 0.5, 3.0, 0.2, 0.2, 2.0, 0.2,',
       '20.0, 15.0, 5.0, 2.5, 2.0, 1.0, 1.0, 0.5, 0.3, 0.3, 0.2,',
       '30.0, 5.0, 5.0, 5.0, 4.0, 3.1, 3.0, 2.0, 2.0, 1.0, 1.0, 0.1, 0.1, 10.0,',
       '6.0, 1.0, 0.5, 0.5, 0.5, 1.0,',
       '12.0, 3.0, 1.5, 1.5, 1.0, 0.5, 0.5, 0.5, 0.5, 0.3, 0.3, 30.0,',
       '72,', '180,', '28,', ',', '140,', '100,', '240,161,', '43,',
       '124,', '24,460,', '320,', '100,250,', '0,', '50,', '135,200,60,',
       '120,60,', '40,60,', '40,40,', '200,500,', '450,450,960,',
       '300,,,254,100,', '680,', '500,40,', '350,80,', '230,150,',
       '10,25,', '210,100,', '450,60,', '300,100,25,', '680,150,',
       '120,40,120,', '350,80,50,', '208,,150,,28,', '85,100,', '75,110,',
       '120,', '70,110,', '80,', '120,80,', '40,', '125,', '150,',
       '90,80,', '70,150,', '30,', '120,,100,', '60,80,', '40,30,',
       '150,60,', '30,50,', '150,70,', '100,120,', '150,80,60,', '90,',
       '45,', '80,25,', '75,', '210,', '130,', '245,', '240,', '200,',
       '110,', '230,', '70,', '44,', '38,', '104,', '73,', '186,', '98,',
       '276,', '196,', '901,', '483,', '34,', '42,', '39,', '68,', '128,',
       '181,', '512,', '360,', '421,', '198,', '428,', '260,', '153,',
       '18,', '18,204,', '20,', '109,208,', '140,86,', '62,48,', '49,',
       '60,', '380,172,', '460,', '208,', '40,,96,', '204,', '418,',
       '378,', '104,60,40,', '436,', '816,96,', '414,', '370,404,126,',
       '810,496,210,', '60,242,48,', '160,100,110,', '480,320,180,210,',
       '118,152,130,', '230,42,55,132,55,', '471,', '152,0,138,910,',
       '160,140,', '142,60,68,140,208,60,', '142,118,', '160,', '370,60,',
       '41,', '63,36,', '48,0,0,341,81,', '260,0,0,910,201,', '523,',
       '352,', '380,', '186,104,', '68,89,0,114,124,', '308,68,',
       '410,283,', '20,5,3,', '30,10,10,3,2,', '30,4,20,2,', '10,40,5,',
       '20,150,', '5,5,10,3,', '50,20,10,5,', '10,8,4,5,', '15,3,5,',
       '15,5,35,', '20,10,3,5,', '50,10,8,', '30,10,10,', '20,20,',
       '1,1,', '10,8,', '8,5,', '5,3,5,', '3,5,3,', '10,10,2,', '10,3,4,',
       '8,5,6,', '20,10,5,', '10,', '4,', '5,5,', '70,10,', '35,',
       '300,10,', '30,20,', '100,5,', '40,8,', '15,', '60,20,', '300,',
       '80,10,', '1000,', '60,5,', '500,', '400,', '120,30,', '250,',
       '5,', '100,20,5,', '10,10,10,', '200,30,300,', '5,200,',
       '20,20,20,20,', '70,30,100,', '20,100,', '100,40,', '60,40,',
       '10,20,', '10,20,20,', '30,10,30,', '40,20,10,', '30,10,',
       '40,20,20,', '30,10,200,', '5,10,', '10,10,', '20,20,20,',
       '30,30,10,', '20,40,10,', '10,40,', '30,10,15,', '25,20,20,',
       '60,30,20,', '20,10,', '40,30,10,20,', '5,20,10,', '200,20,100,',
       '200,200,40,', '10,30,400,', '40,20,100,', '5,15,20,50,',
       '20,10,20,', '10,60,30,10,', '300,20,', '5,10,10,', '5,15,',
       '20,200,', '40,15,', '5,20,5,', '25,', '12,', '32,', '8,', '7,',
       '6,', '3,', '10,30,', '3,10,200,', '3,200,', '3,40,', '200,200,',
       '1500,500,', '900,600,', '1600,900,', '300,200,', '600,400,',
       '800,100,', '300,300,', '700,500,', '500,300,', '400,300,',
       '150,250,', '20,5,15,5,', '15,5,5,10,', '15,15,5,', '15,5,10,10,',
       '2100,400,400,', '15,20,5,10,', '30,5,10,20,', '15,15,5,5,',
       '15,20,', '15,20,10,5,10,', '30,20,20,10,', '12,8,10,5,10,',
       '10,5,5,5,10,', '15,10,5,10,5,', '15,10,10,', '10,15,15,',
       '20,20,15,', '10,15,5,10,5,', '15,5,10,5,', '150,100,', '600,',
       '400,200,', '600,200,', '1500,400,200,', '500,200,400,',
       '1700,800,', '300,500,', '1000,500,', '200,100,', '300,100,',
       '500,200,', '1000,300,', '1100,300,', '200,150,200,50,',
       '30,100,100,50,', '150,270,60,170,50,', '150,230,40,130,50,',
       '70,50,20,70,40,', '80,50,10,30,30,', '1100,', '700,',
       '200,30,10,120,', '170,70,20,70,', '210,70,10,60,',
       '220,30,20,40,', '100,10,30,', '70,30,10,50,', '120,20,10,40,',
       '110,30,', '150,70,20,70,40,10,', '150,30,30,50,30,10,',
       '40,20,10,30,10,', '60,20,10,20,20,', '2000,', '1200,',
       '1500,200,300,', '800,100,200,', '700,200,100,', '300,200,300,',
       '400,200,200,', '30,10,20,10,5,5,15,', '15,10,5,5,15,',
       '1000,200,200,200,', '15,25,', '250,200,150,100,', '150,50,',
       '400,100,', '80,40,60,', '60,50,110,', '50,30,60,', '50,40,70,',
       '30,20,20,', '20,10,10,', '20,20,10,', '10,15,5,',
       '200,100,120,100,', '50,20,40,100,', '60,140,80,60,30,30,',
       '40,160,70,70,20,', '70,20,50,40,50,20,', '40,30,70,30,30,20,',
       '50,40,30,50,80,', '30,60,120,50,', '30,60,80,', '20,40,70,',
       '300,50,20,', '200,50,50,', '700,200,500,', '500,100,500,',
       '1100,200,800,', '100,500,', '300,400,300,',
       '40,10,10,5,8,20,2,10,60,', '30,15,30,16,30,30,10,18,100,',
       '20,6,20,8,15,10,20,40,10,', '15,2,10,12,30,10,7,30,2,',
       '145,10,3,,10,2,7,5,5,100,', '100,30,15,2,5,10,5,50,',
       '100,15,17,5,7,7,50,80,', '30,5,5,3,5,12,5,15,',
       '20,2,5,25,5,5,15,70,', '15,5,15,10,4,3,13,25,',
       '46,2,5,15,6,10,30,20,', '20,5,5,20,2,12,30,', '15,2,7,2,10,2,',
       '10,1,5,15,5,7,5,', '30,6,4,5,7,13,15,', '35,4,2,7,,',
       '20,3,5,3,11,10,', '15,2,7,4,9,', '155,30,5,15,15,5,10,25,2,50,',
       '25,20,3,30,15,20,5,5,10,25,', '40,12,7,20,2,10,15,3,5,40,',
       '35,15,2,10,5,2,2,15,50,5,30,', '80,8,3,15,5,20,3,25,',
       '35,15,2,50,5,15,3,5,3,40,', '25,20,5,20,15,10,4,3,10,',
       '40,30,3,12,2,10,10,7,5,20,', '115,20,2,20,30,5,4,40,25,',
       '25,15,20,15,10,3,5,5,5,10,3,30,5,4,85,', '30,17,5,8,2,5,2,30,15,',
       '20,8,10,10,3,2,4,20,', '25,25,7,10,2,20,', '65,15,8,5,2,25,',
       '35,30,5,11,15,', '50,20,25,', '1700,', '800,', '300,700,200,',
       '4,50,25,15,10,5,10,6,2,3,50,', '70,15,15,8,10,3,25,14,4,30,',
       '30,6,25,8,3,15,2,20,', '10,20,10,15,14,2,2,20,3,15,',
       '8,20,40,5,11,15,5,4,3,20,100,', '20,12,15,3,6,8,5,7,2,50,',
       '30,20,23,10,9,3,8,3,12,3,7,20,',
       '23,8,12,20,35,5,6,23,4,2,20,2,15,', '6,60,17,10,3,15,15,10,',
       '8,10,7,8,12,10,1,30,8,10,70,3,,30,',
       '8,20,15,4,15,4,20,20,8,6,15,50,', '15,35,12,15,50,6,2,15,30,',
       '6,15,8,5,10,30,18,12,5,15,', '9,20,4,3,30,15,20,20,10,',
       '20,10,10,25,15,14,5,15,', '14,25,4,20,15,10,20,9,7,15,20,',
       '20,8,8,40,12,10,20,', '50,5,25,15,32,6,', '220,90,10,80,',
       '180,50,40,30,', '80,30,30,', '120,20,20,', '500,1000,',
       '50,30,80,', '40,30,30,100,', '10,15,', '60,35,', '30,40,',
       '50,120,50,', '15,8,5,15,5,5,10,12,14,30,25,',
       '50,4,20,8,3,3,10,30,15,', '20,3,3,12,4,4,3,5,3,10,',
       '15,8,8,3,5,3,7,6,5,', '30,5,10,7,20,7,40,2,15,',
       '20,2,10,3,15,4,12,15,4,8,20,', '15,5,6,5,5,2,4,12,',
       '30,2,2,3,15,10,50,4,4,', '50,10,3,10,3,12,5,3,6,',
       '25,2,5,4,4,5,10,10,', '15,10,2,10,7,3,7,', '20,7,15,5,2,2,30,15,',
       '15,15,3,10,9,12,7,13,', '25,10,10,3,12,5,4,5,',
       '15,3,10,2,9,3,4,', '15,12,20,2,11,15,3,8,',
       '20,8,12,30,3,7,2,7,1,15,', '5,4,15,10,4,10,1,6,16,',
       '200,900,100,', '250,7,', '25,20,15,5,3,5,', '12,5,5,2,2,10,11,',
       '1200,500,', '200,1100,', '200,1000,', '100,1300,', '50,500,',
       '50,400,', '100,350,', '30,15,150,',
       '35,10,4,5,10,10,8,15,5,8,4,15,5,5,30,',
       '30,20,15,2,5,10,15,5,45,', '30,3,10,5,29,10,7,5,5,10,4,7,10,11,',
       '20,13,13,15,45,15,', '35,15,4,4,3,7,10,20,3,10,35,',
       '30,3,15,2,12,30,3,15,', '35,5,17,8,16,3,35,3,18,5,6,8,',
       '35,20,10,5,7,5,5,10,', '20,12,10,4,5,15,10,20,10,12,15,60,50,',
       '15,5,10,13,3,7,45,2,10,', '50,12,10,10,22,2,5,5,15,10,5,5,3,50,',
       '40,10,4,20,8,13,5,2,4,3,25,', '50,5,15,15,22,5,20,18,10,5,6,17,',
       '25,13,5,14,7,5,7,12,3,30,', '30,15,5,10,10,5,5,6,5,3,50,',
       '15,5,3,14,8,4,5,5,10,10,20,', '5,4,6,3,5,50,',
       '15,10,7,5,15,3,20,30,', '70,2,5,10,10,5,5,5,5,6,20,',
       '35,7,3,5,5,40,6,30,', '20,5,10,5,5,4,3,6,40,',
       '15,5,8,5,2,6,10,5,20,10,30,', '25,5,5,7,15,5,3,5,3,15,50,',
       '10,20,3,10,3,15,20,25,', '10,10,5,15,3,5,',
       '20,10,8,10,3,10,3,3,5,5,', '30,15,20,5,10,10,5,5,10,',
       '20,10,30,7,3,12,4,25,', '30,10,35,15,15,10,5,6,30,',
       '10,7,5,20,7,20,3,15,', '25,5,2,7,3,5,20,',
       '20,5,10,8,15,6,10,15,', '70,20,30,', '50,30,40,', '80,50,50,',
       '25,15,50,30,', '120,100,20,70,', '155,85,30,', '155,10,300,',
       '250,30,', '30,500,', '200,100,100,100,', '50,70,50,100,',
       '700,200,', '800,300,', '100,15,170,', '100,15,', '700,300,',
       '250,100,', '50,200,', '120,20,', '25,30,50,', '100,200,100,50,',
       '100,50,30,20,', '100,150,', '200,150,60,', '150,100,30,50,20,',
       '60,50,10,70,30,', 0, '10,15,30,', '5,40,', '20,50,100,',
       '200,140,', '100,70,30,', '200,115,', '100,80,20,50,', '280,',
       '200,30,50,300,', '250,130,', '100,300,',
       '25,15,5,15,25,15,5,20,10,20,5,10,15,',
       '50,20,10,5,20,15,10,15,5,30,10,20,',
       '20,30,10,10,10,12,10,2,25,10,',
       '20,15,15,5,20,10,5,20,5,10,25,3,20,30,',
       '25,10,20,15,5,15,5,10,5,25,', '50,20,10,5,15,5,5,10,30,5,15,20,',
       '20,20,5,10,15,5,5,5,5,3,5,20,2,10,25,',
       '35,5,10,15,10,5,5,5,10,3,10,50,',
       '30,10,5,10,10,25,5,5,20,15,5,10,25,',
       '2,5,10,10,15,10,10,5,15,5,3,20,10,5,5,30,', '300,800,',
       '200,1200,500,', '150,150,80,120,50,60,', '100,50,70,180,50,40,',
       '150,50,50,', '150,50,40,50,', '60,20,8,30,', '30,20,40,30,',
       '10,30,40,', '50,40,20,', '20,60,130,', '100,50,', '20,50,40,60,',
       '10,70,30,30,', '50,20,40,', '100,100,50,30,', '30,20,30,10,20,',
       '100,50,50,60,30,20,40,40,', '10,20,5,', '30,40,5,', '20,30,',
       '20,30,15,', '15,10,', '15,5,', '50,40,10,', '70,30,200,',
       '60,40,50,', '30,70,50,', '10,50,130,', '10,50,10,60,',
       '20,50,10,', '5,60,15,15,', '20,50,10,5,', '40,70,10,20,',
       '15,40,5,20,20,', '25,40,5,10,40,', '1500,', '20,50,30,20,',
       '30,100,10,50,40,', '20,120,50,10,', '10,200,20,50,',
       '10,150,20,30,', '50,10,', '70,30,10,10,30,20,', '30,30,20,30,',
       '50,20,30,', '10,12,20,', '40,30,10,40,20,', '50,40,50,40,',
       '1000,50,18,15,', '30,5,10,3,2,20,15,', '15,5,15,2,5,3,20,',
       '20,8,2,5,5,3,10,', '30,10,10,5,5,3,4,15,10,',
       '25,5,2,3,10,5,4,15,', '10,5,10,10,5,10,5,', '10,15,2,3,10,5,15,',
       '15,5,3,10,15,10,10,', '30,5,15,5,50,30,', '15,5,6,2,5,2,10,',
       '25,15,10,10,15,', '30,20,3,10,5,3,2,5,5,15,',
       '20,15,5,2,10,3,15,2,5,', '15,10,10,4,15,10,50,', '10,7,5,3,15,',
       '20,7,3,3,2,2,13,10,', '10,10,13,10,3,3,20,', '20,5,1,5,10,',
       '50,120,40,40,', '40,10,50,125,', '10,10,20,75,', '100,15,5,30,',
       '30,20,50,60,', '50,80,', '100,20,10,60,', '20,40,20,',
       '15,50,10,30,', '10,30,50,', '5,10,30,', '30,10,20,', '15,5,30,',
       '20,60,10,', '20,20,10,20,10,', '10,40,50,',
       '20,5,10,5,5,15,12,5,25,3,15,', '15,3,10,5,7,2,3,2,5,10,11,5,25,',
       '35,3,5,5,3,15,3,3,20,', '10,10,15,12,10,10,4,5,5,5,',
       '15,2,2,5,5,15,4,7,4,50,', '25,2,6,20,15,5,8,15,4,25,',
       '35,5,10,5,20,15,3,3,10,', '20,10,1,10,6,4,5,10,10,8,2,5,2,10,35,',
       '30,10,5,5,5,4,2,3,10,', '10,30,4,12,5,5,5,8,15,10,5,2,20,',
       '20,10,25,10,3,2,4,', '15,3,5,6,5,5,5,4,30,8,',
       '20,10,3,15,5,3,10,2,5,15,4,15,', '40,5,5,10,5,5,',
       '30,10,2,15,10,5,5,15,4,', '10,10,2,5,8,20,2,5,',
       '15,3,2,6,8,10,10,3,5,', '10,5,10,2,5,12,15,5,2,6,',
       '15,5,5,6,5,5,2,', '10,10,2,12,15,11,', '10,50,', '10,40,10,5,',
       '5,100,7,', '20,10,20,10,10,', '10,10,15,20,', '20,50,20,10,',
       '500,500,200,', '20,50,20,10,20,20,', '50,10,20,20,', '10,30,20,',
       '20,10,50,', '10,90,30,', '10,15,5,30,20,', '10,10,50,',
       '4,15,5,20,60,40,', '20,10,5,40,10,', '100,200,50,100,',
       '150,50,250,', '1300,', '5,10,8,', '63,20,', '142,', '80,70,',
       '2,70,,', '158,105,', '20,35,', '44,19,37,', '58,34,',
       '7,2,60,8,104,', '475,3,40,4,10,', '38,58,', '4,60,60,',
       '2,68,15,', '48,', '65,35,', '39,21,', '37,30,', '31,', '52,',
       '59,40,', '2,132,17,', '20,16,,', '11,22,5,', '16,', '126,', '55,',
       '2,', '4,120,92,', '2,100,', '64,', '90,44,', '2,46,', '26,',
       '106,', '42,7,', '58,', '9,', '4,35,4,4,', '4,6,', '12,5,', '4,4,',
       26, '4,20,', '1,', '62,', '130,6,', '19,', '6,8,24,', '16,38,',
       '23,', '109,', '2,4,', '95,10,', '12,3,', '6,2,', '62,56,',
       '1,6,4,', '1,2,', '101,20,', '76,2,', '20,95,', '7,8,4,', '176,',
       '38,32,2,1,', '343,2,', '58,128,', '54,', '86,1,', '102,', '90,3,',
       '46,20,', '27,', '7,9,', '60,7,100,,', '3,25,', '91,', '96,',
       '35,34,60,', '36,75,', '55,55,', '2.5,1.5,5.6,1.5,8.5,2,1.9,',
       '2,0.9,2.3,1,11,1.3,0.5,1,', '0.65,1.2,2.5,1.5,12,1.9,1,0,0.45,',
       '0,1.5,1.7,1.5,8.5,0.5,0.8,0.5,1,', '0,0.7,0,0,8.7,0,0.7,0.9,0,',
       '0,0.5,1.2,0,8.3,0.8,0.9,0.3,0.2,',
       '1.6,1.5,2,0.9,7.1,1.4,0,0.3,2.1,',
       '1.2,2.1,3.1,1.5,5,1.1,0.5,0.8,0.5,',
       '2,1,1.5,,0.1,2,0.5,0.5,0.2,0.2,0.1,0.8,0.2,1,2.5,3.5,0.2,0.2,0.5,0.05,0.1,2,2,1,0.5,1.5,3,34.7,',
       '2,0.2,0.2,0.8,1,4,0.15,2,1,0.2,0.3,0.3,0.1,0.2,2.5,0.4,0.1,0.5,0.1,27,',
       '0.4,0.5,0.26,0.8,0.2,0.4,0.2,0.4,0.6,0.2,0.1,0.3,0.6,1.5,2.6,0.1,0.3,0.48,0.2,1.3,2.5,0.5,0.1,0.5,18,',
       '2.3,0.5,0.3,1.5,2.5,0.2,0.2,0.6,15,1,1,0.3,0.8,2.8,1,0.2,0.3,0.5,0.3,0.2,0.5,0.3,0.5,0.1,0.7,0.1,0.5,0.1,1.5,37.9,',
       '1.7,0.1,1.2,0.1,1.6,0.2,2,0.2,0.4,1,0.2,0.1,0.2,1,1.3,0.5,0.1,0.1,0.4,0.1,0.1,0.3,0.5,0.3,0.6,19.6,',
       '2,0.1,0.2,0.1,1,4,0.15,2,1,0.2,2,0.3,0.2,2.5,0.4,0.1,0.5,0.2,0.1,23.6,',
       '0.7,0.5,1.5,0.5,1.5,0.5,0.2,1,0.7,1.5,0.5,0.8,0.8,0.2,1.3,0.1,0.1,0.5,2.6,0.8,0.2,0.5,0.5,0.1,0.5,1.4,2.6,2,0.3,0.4,0.4,5.3,0.3,27,',
       '0.02,0.5,0.4,0.1,0.6,0.1,0.5,1.6,0.5,0.5,0.6,1.3,0.1,0.2,2,0.5,0.4,0.23,0.5,0.5,1.5,0.5,2.3,34,',
       '1,0.6,0.5,0.15,1,0.1,0.2,0.5,0.1,2,0.4,1.3,21.3,',
       '2.5,0.5,1.2,0.5,2,0.1,0.5,0.2,2,2,0.5,1.5,0.3,0.1,1.5,1.2,0.2,2.5,3.5,0.5,0.5,0.5,0.05,0.4,0.1,1,1.5,0.1,1,23.5,',
       '0.5,2.3,0.8,0.5,0.5,0.5,0.7,1,0.2,2,0.5,0.5,0.1,0.2,1,0.5,0.1,2,0.1,0.2,2.5,1.3,2.3,0.2,1.5,0.2,22.6,',
       '0.3,2.5,1.6,1.5,0.5,2,0.8,1.6,0.3,1.9,2.3,0.8,0.6,0.7,1.5,2.6,0.8,1,1.2,0.6,0.6,0.25,2,2,1.6,1.1,0.1,0.6,2.3,21.5,',
       '2,1,2,2,0.5,0.5,0.5,0.1,0.2,1,2.3,0.5,0.2,0.2,0.5,0.05,0.1,1.2,2,0.5,1.5,3,38,',
       '0.2,0.2,0.2,1,0.15,2,1,0.2,0.3,2,0.3,0.1,0.2,2.5,0.4,0.1,0.5,0.1,35,',
       '1.5,0.5,0.5,2,1,1,0.2,0.1,3.5,1.5,0.5,0.1,2.5,1.5,3,35,',
       '3,0.5,0.5,1.2,1.5,1,0.3,2.5,3.5,0.1,0.5,0.3,42,',
       '0.2,1.5,0.2,2,2.5,3,0.8,0.5,0.5,1,0.2,2.5,0.5,0.1,0.3,0.2,1,2.6,2.5,0.2,1,0.1,0.1,1.5,1.8,1.5,1,1.5,39,',
       '1,2.5,1.2,0.2,0.1,1.5,1,0.8,0.8,0.2,1.2,1.3,0.2,0.1,0.2,2.5,1.5,2.5,0.1,0.2,42,',
       '30,0.5,0.5,0.1,1,1.2,0.5,1.8,1.3,0.1,0.2,0.3,0.4,0.23,0.5,0.5,1.5,0.5,2.3,34,',
       '1,1.7,0,1.2,0.15,1,0.1,0.2,0.5,0.5,0.1,2,0.4,1.3,21.3,',
       '0.5,0.5,0.3,0.78,1.5,0.5,1,0.5,2.5,0.3,0.2,2,2,0.2,3.5,0.3,0.2,0.3,1.5,0.5,2.5,0.3,0.5,1.5,25,',
       '1,1.6,0.5,1.1,1,0.2,0.3,0.6,0.3,0.1,2.6,2.3,0.8,31.5,',
       '0.2,0.5,0.6,1.5,2.5,1,0.8,2.5,0.5,0.6,1.8,1.2,1.8,2.3,2.2,0.2,0.2,0.3,0.6,2.6,0.5,3,0.3,0.5,2.5,38.5,',
       '1,2.3,1.3,0.1,1.3,0.1,0.2,3.4,4,1,41,',
       '0.8,0.3,0.3,0.78,1.5,0.5,1,0.5,2.5,0.3,0.2,2,2,0.2,2,2.6,0.3,0.2,0.3,1.5,2.5,2.5,0.3,0.5,1.5,39.5,',

In [46]:
final.loc[final['MAJOR_SPECIES'] == 'No Catch','TOTAL_CATCH']= 0
final.loc[final['MAJOR_SPECIES'] == 'Acetus(5), Sciaenids(10), lobster(3no)', 'TOTAL_CATCH'] = 18
final.loc[final['MAJOR_SPECIES'] == 'No fish,','TOTAL_CATCH']=0

In [47]:
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].astype(str).str.replace('Nil,','nan' )
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].astype(str).str.replace('Catch(kgs),', '', regex=False)
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].astype(str).str.replace(r'kgs?','', regex=True,case=False)
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].str.replace('No','')
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].str.replace('1ton500','1500')
final['TOTAL_CATCH'] = final['TOTAL_CATCH'].str.replace('-','.')

In [48]:
Ton= final[final['TOTAL_CATCH'].str.contains('ton', na=False, case=False)].copy()
Ton['TOTAL_CATCH']=Ton['TOTAL_CATCH'].astype(str).str.replace('ton', '', case=False).astype(float)*1000

In [49]:
final.loc[Ton.index, 'TOTAL_CATCH'] = Ton['TOTAL_CATCH']

In [50]:
AZ=final[final['TOTAL_CATCH'].str.contains('[A-Za-z]', regex=True, na=False) & (final['TOTAL_CATCH'].astype(str).str.lower() != 'nan')
].copy()
AZ['TOTAL_CATCH']=AZ['TOTAL_CATCH'].astype(str).str.findall(r'\d+\d*').str.join(',')

In [51]:
final.loc[AZ.index, 'TOTAL_CATCH'] = AZ['TOTAL_CATCH']

In [52]:
spliting=final[pd.to_numeric(final['TOTAL_CATCH'], errors='coerce')>=20000].copy()

In [53]:
import split_catch
spliting['TOTAL_CATCH'] = spliting.apply(split_catch.split_catch,axis=1)

In [54]:
final.loc[spliting.index, 'TOTAL_CATCH'] = spliting['TOTAL_CATCH']

In [55]:
final[final['TOTAL_CATCH'].astype(str).str.contains(',', na=False, regex=True)]

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
981,2013-06-27,9.220,76.130,"500,250,500,500","Indian mackerel,M.dobsoni, M.affinis, Eculosa ..."
986,2013-08-20,9.120,76.190,"500,800","mackerel, oil sardine"
987,2013-09-11,10.300,76.200,"500, 1500, 300","Indian mackerel, oil sarine, Anchovy"
988,2013-09-28,9.450,76.080,"200, 1200, 1000","Indian mackerel, oil sardine, anchovy"
989,2014-01-10,13.150,74.280,"0.2,,0.1,,,0.6,1.5,,,,,,,,,,,,,,0.1,,,,2,,,0.5...","Saurida tumbil,Anodontostoma chacunda,Sardinel..."
...,...,...,...,...,...
3205,2016-10-13,11.374,80.092,"7,2,1,","Sardinella longiceps,Siganus sp.,Leiognathus d..."
3206,2016-11-03,11.331,80.431,"5,2,3,1,","Sardinella longiceps,Sardinella albella,Sardin..."
3207,2016-08-23,11.196,81.509,"15,24,5,3,","Scomberoides commersonianus,Sardinella longice..."
3208,2016-10-13,11.405,80.254,"15,9,5,8,11,6,","Sardinella longiceps,Siganus sp.,Carangoides s..."
3209,2016-11-03,11.338,80.607,"7,6,15,7,4,","Sardinella gibbosa,Carangoides sp.,Sardinella ..."

In [56]:
Comma=final[final['TOTAL_CATCH'].astype(str).str.contains(',', na=False, regex=True)].copy()
Comma['TOTAL_CATCH'] = Comma['TOTAL_CATCH'].apply( lambda x: round(sum(float(i) for i in x.split(',') if i.strip() != ''), 3))

In [57]:
final.loc[Comma.index, 'TOTAL_CATCH'] = Comma['TOTAL_CATCH'].astype(str)

In [58]:
final['TOTAL_CATCH'] = pd.to_numeric(final['TOTAL_CATCH'], errors='coerce')

In [59]:
final

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
0,2009-02-19,18.455278,84.431111,390.0,"Longfish(200), Ponyfish(90), Nemipters(50), Up..."
1,2009-02-14,18.445000,84.494167,1000.0,"Drab crocker(500), Mackeral(200), Dieddaba(200..."
2,2009-02-19,18.240833,84.161667,500.0,"Pomfret(400), Ponyfish(100)"
3,2009-02-12,17.993611,83.774444,550.0,"Drab croaker(200), Nemipters(125), Upenius(125..."
4,2009-03-08,17.708056,83.390000,95.0,"Drabcrocker(50), Nemipters(20), Lizardfish(10)..."
...,...,...,...,...,...
3205,2016-10-13,11.374000,80.092000,10.0,"Sardinella longiceps,Siganus sp.,Leiognathus d..."
3206,2016-11-03,11.331000,80.431000,11.0,"Sardinella longiceps,Sardinella albella,Sardin..."
3207,2016-08-23,11.196000,81.509000,47.0,"Scomberoides commersonianus,Sardinella longice..."
3208,2016-10-13,11.405000,80.254000,54.0,"Sardinella longiceps,Siganus sp.,Carangoides s..."
3209,2016-11-03,11.338000,80.607000,39.0,"Sardinella gibbosa,Carangoides sp.,Sardinella ..."

In [60]:
data.loc[final.index, 'TOTAL_CATCH'] = final['TOTAL_CATCH']

In [62]:
data[data['FISHING_START'].duplicated(keep=False) & data['SHOOT_LAT'].duplicated(keep=False) & data['SHOOT_LONG'].duplicated(keep=False)]

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
18,2009-03-19 00:00:00,16.981111,82.482222,60.0,"Ponyfish(30), Nemipters(8), Lizardfish(5), Arc..."
19,2009-04-14 00:00:00,16.981111,82.482222,220.0,"Longfin(70), Lizardfish(52), ponyfish(40), Nem..."
21,2009-01-08 00:00:00,15.982942,81.254517,184.0,"white pomferts(40), pulasa(60), garaka(60), ri..."
22,2009-01-08 00:00:00,15.982942,81.254517,126.0,"Pomfrets(10),Blach pomfrets(3), Goraka(35), Pa..."
60,2007-12-13 00:00:00,23.006444,67.518750,2450.0,"Small Croakers, Croakers, Bulleye, Catfish,Pra..."
...,...,...,...,...,...
2951,2016-06-22 05:45:00,20.885417,88.707639,13.0,"Tenualosa ilisha,Otolithes cuvierii,Miscellaneus,"
2952,2016-06-23 06:40:00,20.895139,88.696528,11.0,"Tenualosa ilisha,Miscellaneus,Pampus argenteus,"
2984,2016-06-20 02:20:00,21.380000,88.290000,18.0,"Pampus argenteus,Rastrelliger kanagurta,"
2986,2016-06-22 05:45:00,21.150000,88.590000,13.0,"Tenualosa ilisha,Otolithes cuvierii,Miscellaneus,"
2987,2016-06-23 06:40:00,21.290000,88.430000,11.0,"Tenualosa ilisha,Miscellaneus,Pampus argenteus,"

In [63]:
data[data.duplicated(subset=['FISHING_START', 'SHOOT_LAT', 'SHOOT_LONG'], keep=False)]

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
21,2009-01-08 00:00:00,15.982942,81.254517,184.0,"white pomferts(40), pulasa(60), garaka(60), ri..."
22,2009-01-08 00:00:00,15.982942,81.254517,126.0,"Pomfrets(10),Blach pomfrets(3), Goraka(35), Pa..."
84,2011-02-08 00:00:00,16.930836,72.967678,3535.0,"Megalaspis cordyla (1500), Rastrelliger kanagu..."
85,2011-02-08 00:00:00,16.930836,72.967678,1286.0,"P. Chinensis(08), P. Argenteus(13), L. Duvauce..."
161,2011-02-10 00:00:00,19.352977,71.823625,35.0,"Ribbon fish(30), Squid(5)"
162,2011-02-10 00:00:00,19.352977,71.823625,25.0,"Ribbon fish(5), Squid(20)"
269,2011-06-15 00:00:00,10.333056,75.866667,950.0,"Carangids, Decapterus Russelli"
270,2011-06-15 00:00:00,10.333056,75.866667,175.0,"Carangids, Decapterus Russelli"
344,2008-10-05 00:00:00,9.250000,76.333056,NaN,NaN
345,2008-10-05 00:00:00,9.250000,76.333056,380.0,"Cuttle fish, Shrimps, Shallow water mix, Sepra..."
371,2009-03-06 00:00:00,9.966667,76.133056,1100.0,"Skipjack Tu, Katsuwonus pelamis"
372,2009-03-06 00:00:00,9.966667,76.133056,600.0,"Skipjack Tu, Katsuwonus pelamis"
1004,2013-06-25 00:00:00,17.360000,83.530000,72.0,NaN
1005,2013-06-25 00:00:00,17.360000,83.530000,180.0,NaN
1022,2013-10-02 00:00:00,17.490000,83.590000,700.0,"yellow fin tuna,MARLIN,"
1023,2013-10-03 00:00:00,17.490000,83.590000,1860.0,"yellow fin tuna,MARLIN,SKJ,"
1024,2013-10-05 00:00:00,17.530000,84.030000,654.0,"yellow fin tuna,,,SHARK,SHO,"
1025,2013-10-06 00:00:00,17.450000,83.560000,680.0,"yellow fin tuna,"
1028,2013-10-09 00:00:00,17.510000,84.040000,380.0,"yellow fin tuna,SHO,"
1037,2013-10-02 00:00:00,17.490000,83.590000,700.0,"yellow fin tuna,MARLIN,"
1038,2013-10-03 00:00:00,17.490000,83.590000,510.0,"MARLIN,shark,"
1039,2013-10-05 00:00:00,17.530000,84.030000,425.0,"yellow fin tuna,MARLIN,shark,"
1040,2013-10-06 00:00:00,17.450000,83.560000,830.0,"yellow fin tuna,MARLIN,"
1043,2013-10-09 00:00:00,17.510000,84.040000,386.0,"yellow fin tuna,,shark,,SWO,"
1058,2014-01-02 00:00:00,19.250000,85.440000,30.0,"yellowfin tuna,"
1059,2014-01-04 00:00:00,20.240000,87.530000,40.0,"SWO,"
1060,2014-01-05 00:00:00,20.380000,88.120000,120.0,"SWO,"
1061,2014-01-06 00:00:00,20.450000,88.140000,40.0,"marlin,"
1062,2014-01-08 00:00:00,20.200000,88.290000,220.0,"yellowfin tuna,,skj,"
1063,2014-01-09 00:00:00,20.180000,88.300000,140.0,"yellowfin tuna,Marlin,"
1064,2014-01-13 00:00:00,20.100000,88.000000,70.0,"SWO,YEELOW FIN TUNA,"
1065,2014-01-14 00:00:00,20.020000,87.200000,0.0,NaN
1067,2014-01-20 00:00:00,19.390000,86.200000,0.0,NaN
1069,2014-01-22 00:00:00,19.500000,86.540000,210.0,"YEELOW FIN TUNA,shark,"
1072,2014-01-02 00:00:00,19.250000,85.440000,30.0,"yellowfin tuna,"
1073,2014-01-04 00:00:00,20.240000,87.530000,40.0,"SWO,"
1074,2014-01-05 00:00:00,20.380000,88.120000,120.0,"SWO,"
1075,2014-01-06 00:00:00,20.450000,88.140000,40.0,"Marlin,"
1076,2014-01-08 00:00:00,20.200000,88.290000,220.0,"shark,yellow fin tuna,"
1077,2014-01-09 00:00:00,20.180000,88.300000,290.0,"yellowfin tuna,Marlin,Bet,"
1078,2014-01-13 00:00:00,20.100000,88.000000,70.0,"SWO,YEELOW FIN TUNA,"
1079,2014-01-14 00:00:00,20.020000,87.200000,0.0,NaN
1081,2014-01-20 00:00:00,19.390000,86.200000,0.0,NaN
1083,2014-01-22 00:00:00,19.500000,86.540000,150.0,"yellowfin tuna,"
1084,2014-01-12 00:00:00,19.170000,85.540000,0.0,NaN
1085,2014-01-12 00:00:00,19.170000,85.540000,90.0,"yellowfin tuna,"
1107,2012-06-19 00:00:00,17.030000,83.340000,90.0,"yellowfin tuna,"
1115,2012-06-19 00:00:00,17.030000,83.340000,196.0,"shark,"
1971,2013-04-16 12:15:00,20.150000,67.783333,109.0,"Thunnus albacares,"
1979,2013-05-24 12:15:00,16.116667,71.133333,1.0,"Lagocephalus inermis,"
1997,2013-04-16 12:15:00,20.150000,67.783333,40.0,"Thunnus albacares,"
2001,2013-05-24 12:15:00,16.116667,71.133333,27.0,"G.cuvier,"
2210,2014-10-29 00:00:00,11.134500,92.119360,235.0,"Thunnus albacares ,Sphyraena sp ,Carangoid sp ..."
2211,2014-10-29 00:00:00,11.134500,92.119360,130.0,"Thunnus albacares ,Sphyraena sp ,Carangoid sp ..."

In [64]:
data

,FISHING_START,SHOOT_LAT,SHOOT_LONG,TOTAL_CATCH,MAJOR_SPECIES
0,2009-02-19,18.455278,84.431111,390.0,"Longfish(200), Ponyfish(90), Nemipters(50), Up..."
1,2009-02-14,18.445000,84.494167,1000.0,"Drab crocker(500), Mackeral(200), Dieddaba(200..."
2,2009-02-19,18.240833,84.161667,500.0,"Pomfret(400), Ponyfish(100)"
3,2009-02-12,17.993611,83.774444,550.0,"Drab croaker(200), Nemipters(125), Upenius(125..."
4,2009-03-08,17.708056,83.390000,95.0,"Drabcrocker(50), Nemipters(20), Lizardfish(10)..."
...,...,...,...,...,...
3205,2016-10-13,11.374000,80.092000,10.0,"Sardinella longiceps,Siganus sp.,Leiognathus d..."
3206,2016-11-03,11.331000,80.431000,11.0,"Sardinella longiceps,Sardinella albella,Sardin..."
3207,2016-08-23,11.196000,81.509000,47.0,"Scomberoides commersonianus,Sardinella longice..."
3208,2016-10-13,11.405000,80.254000,54.0,"Sardinella longiceps,Siganus sp.,Carangoides s..."
3209,2016-11-03,11.338000,80.607000,39.0,"Sardinella gibbosa,Carangoides sp.,Sardinella ..."

In [65]:
data= data.drop_duplicates().reset_index(drop=True)

In [66]:
data.drop(columns=['TOTAL_CATCH','MAJOR_SPECIES'], inplace=True)

In [67]:
data.to_excel(r'C:\Users\vodla\Downloads\Incois\input.xlsx', index=False)